### ISSUE TITLE
Migrate to a package in Ska3

### ISSUE THREAD

**Issue by taldcroft** [sot/aimpoint_mon#20]
This should be migrated to a package in Ska3.

First crack at this was disappointing. After running 2to3 on plot_aimpoint.py, it crashed when trying to write out the mpld3 version fo the plot. At this point I'd be OK just punting on that, but still annoying.

```
python plot_aimpoint.py --data-root=data
...
2021-01-02 11:34:57,171 Applying aimpoint jump of {'d_dy': 2.0, 'd_dz': 1.0} at 2016:064
./plot_aimpoint.py:399: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
2021-01-02 11:34:57,825 Writing plot files data/chip_x_y_aciss.png,html
Traceback (most recent call last):
  File "./plot_aimpoint.py", line 472, in <module>
    main()
  File "./plot_aimpoint.py", line 459, in main
    asol_monthly.plot_chip_x_y(info[det_title])
  File "./plot_aimpoint.py", line 405, in plot_chip_x_y
    mpld3.save_html(fig, outroot + '.html')
  File "/Users/aldcroft/miniconda3/envs/ska3/lib/python3.8/site-packages/mpld3/_display.py", line 453, in save_html
    fileobj.write(fig_to_html(fig, **kwargs))
  File "/Users/aldcroft/miniconda3/envs/ska3/lib/python3.8/site-packages/mpld3/_display.py", line 251, in fig_to_html
    figure_json=json.dumps(figure_json, cls=NumpyEncoder),
  File "/Users/aldcroft/miniconda3/envs/ska3/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/aldcroft/miniconda3/envs/ska3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/aldcroft/miniconda3/envs/ska3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aldcroft/miniconda3/envs/ska3/lib/python3.8/site-packages/mpld3/_display.py", line 138, in default
    return json.JSONEncoder.default(self, obj)
  File "/Users/aldcroft/miniconda3/envs/ska3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

```

**Comment by jeanconn** [comment]
I think this was done with #22
